[tool.poetry]
name = "mcsl2"
version = "2.0.0.beta1"
description = "A Minecraft Server Launcher"
authors = ["LxHTT <lxhtz.dl@qq.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
PyQt5 = "==5.15.4"
pyqt5-tools = "^5.15.4.3.2"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
# black = "^23.1.0"
# isort = "^5.12.0"
Nuitka = "^1.4.8"
ordered-set = "^4.1.0"
zstandard = "^0.20.0"

[tool.black]
extend-exclude = "(MCSL2_Icon.py)"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
