[project]
name = "MCSL2"
dynamic = ["version"]
description = ""
authors = [
    {name = "MCSLTeam", email = "lxhtt@vip.qq.com"},
]
dependencies = [
    "PyQt5==5.15.10",
    "PyQt-Fluent-Widgets[full]>=1.3.8",
    "psutil==5.9.5",
    "loguru==0.7.2",
    "requests==2.31.0",
    "aria2p==0.11.3",
    "ordered-set==4.1.0",
    "nuitka>=1.9",
    "imageio>=2.31.5",
    "pyqt5-qt5==5.15.2",
    "setuptools>=69.0.2",
    "lib-not-dr>=0.1.8",
    "pyqt5-stubs>=5.15.6.0",
]
requires-python = ">=3.8,<3.9"
readme = "README.md"
license = {text = "GPL-3.0"}

[tool.setuptools.dynamic]
version = { attr = "MCSL2Lib.MCSL2VERSION" }

[project.optional-dependencies]
tomli = ["tomli>=2.0.1"]
ruff = ["ruff>=0.1.6"]

[tool.pdm.scripts]
main = "python MCSL2.py"
build = "python lndl_build.py -y"
build_github = "python lndl_build.py --github"

[tool.ruff]
target-version = "py38"
line-length = 120
src = [
    "MCSL2Lib",
    "PluginExample",
    "Tools",
    "Adapters",
]
