[project]
name = "MCSL2"
dynamic = ["version"]
description = "MC server launcher 2"
authors = [
    {name = "MCSLTeam", email = "lxhtt@vip.qq.com"},
    {name = "shenjackyuanjie", email = "3695888@qq.com"},

    # 还是加一下吧(
]
dependencies = [
    "setuptools>=60", # 随便指定个版本就好 (
    # qt
    "PyQt5==5.15.10",
    "PyQt-Fluent-Widgets[full]>=1.3.8",
    "pyqt5-qt5==5.15.2",
    # 系统信息
    "psutil==5.9.5",
    "loguru==0.7.2",
    "requests==2.31.0",
    "aria2p==0.11.3",
    # 构建需要
    "lib-not-dr[nuitka]>=0.2.0",
    "nuitka>=1.9.1",
    "imageio>=2.31.5",
]
requires-python = ">=3.8,<3.9"
readme = "README.md"
license = {text = "GPL-3.0"}

[tool.setuptools.dynamic]
version = { attr = "MCSL2Lib.MCSL2VERSION" }

[tool.setuptools]
package = []
# 实际上并不发布包 (用于解决无法 pdm install) 

[project.optional-dependencies]
all = [
    "tomli>=2.0.1",
    "ruff>=0.1.6",
    "pyqt5-stubs>=5.15.6.0"
]

[tool.pdm.scripts]
main = "python MCSL2.py"
build = "python -m lndl_nuitka . -y"
build_github = "python -m lndl_nuitka . -y -- --disable-console"

[tool.ruff]
target-version = "py38"
line-length = 100
src = [
    "MCSL2Lib",
    "PluginExample",
    "Tools",
    "Adapters",
]
output-format = "grouped"
preview = true

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "W", # pycodestyle
]
ignore = ["I001"]

[tool.ruff.lint.isort]
force-single-line = true
force-wrap-aliases = true
combine-as-imports = true

# 请使用 lndl_nuitka . -y 编译 (-y 为自动确认)
[tool.lndl.nuitka]
main = "MCSL2.py"
output-dir = "build"

# 编译选项
clang = true
msvc = "latest"
standalone = true
lto = "yes"
disable-console = false
show-memory = false
show-progress = false

# 版本号 可通过 Tools/update-pyproject.py 更新
product-version = "2.2.3.0"
file-version = "0.3.1.0"

# 文件信息
product-name = "MCSL 2"
company-name = "MCSL Team"
file-description = "MC Server Launcher 2"
copyright = "Copyright ©MCSL Team. All right reserved."

# 依赖
include-package = ["MCSL2Lib", "sqlite3"]
include-data-dir = [["MCSL2/Aria2", "MCSL2/Aria2"]]
follow-import-to = ["Adapters", "loguru", "requests"]
nofollow-import-to = ["numpy", "scipy", "PIL", "colorthief"]

enable-plugin = ["pyqt5"]
windows-icon-from-ico = "MCSL2.ico"
assume-yes-for-download = true
