name: Build with Nuitka

on: [push, workflow_dispatch]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install Necessary Packages
        run: |
          python -m pip install poetry pip setuptools tomlkit -U

      - name: Install Deps for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libfuse2

      # win 上 poetry 的奇怪 bug 导致 poetry install 装不上依赖
      - name: Install Deps
        run: |
          python .github/utils/install_deps.py

      - name: Build Executable
        run: >
          poetry run
          nuitka
          --standalone --show-progress --show-memory
          --enable-plugin=pyqt5 --onefile
          --windows-disable-console --windows-icon-from-ico=pack.ico --windows-company-name="LxHTT"
          --windows-product-name=MCSL2 --windows-file-version=2.0.0 --windows-product-version=2.0.0
          --windows-file-description="A Minecraft Server Launcher"
          main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
