name: Build and Release

on: workflow_dispatch

permissions: write-all

jobs:
  Windows:
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
        architecture:
          - x64
          - x86
          - arm64
        mcsl2version: 
          - 2.2.1.1

    runs-on: ${{ matrix.os }}

    steps:

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Update Pip and Install Requirements
        run: |
          python -m pip install pip setuptools -U
          python -m pip install -r requirements.txt
          python -m pip uninstall numpy -y
          python -m pip uninstall scipy -y

      - name: Build on Windows
        run: >
          python -m nuitka
          --standalone
          --clang
          --msvc=latest
          --enable-plugin=pyqt5
          --disable-plugin=multiprocessing
          --nofollow-import-to=scipy
          --nofollow-import-to=numpy
          --output-dir=build
          --assume-yes-for-downloads
          --windows-icon-from-ico=MCSL2.ico
          --disable-console
          --company-name="MCSL Team"
          --product-name="MCSL 2"
          --file-version=${{ matrix.mcsl2version }}
          --product-version=${{ matrix.mcsl2version }}
          --windows-file-description="MC Server Launcher 2"
          --include-data-dir=resource/dark=resource/dark
          --include-data-dir=resource/light=resource/light
          --include-data-dir=MCSL2/Aria2=MCSL2/Aria2
          --follow-import-to=Adapters
          --follow-import-to=MCSL2Lib
          --copyright="Copyright ©MCSL Team. All right reserved."
          --lto=no
          --remove-output
          MCSL2.py

      - name: Delete Useless Files and Compress with upx
        run: |
          cd build
          cd MCSL2.dist
          cmd /K rmdir /s /q certifi
          cmd /K rmdir /s /q zstandard
          cmd /K del /f /q _asyncio.pyd
          cmd /K del /f /q _multiprocessing.pyd
          cmd /K del /f /q _queue.pyd
          cmd /K del /f /q libeay32.dll
          cmd /K del /f /q pyexpat.pyd
          cmd /K del /f /q qt5qml.dll
          cmd /K del /f /q qt5qmlmodels.dll
          cmd /K del /f /q qt5quick.dll
          cmd /K del /f /q ssleay32.dll
          cd ..
          cd ..
          .\upx.exe -9 .\build\MCSL2.dist\*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-${{ runner.os }}-${{ matrix.architecture }}
          path: |
            build/MCSL2.dist/**/*

  Linux:
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64
          - x86
          - arm64
        mcsl2version: 
          - 2.2.1.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Update Pip and Install Requirements
        run: |
          python -m pip install pip setuptools -U
          python -m pip install -r requirements.txt
          python -m pip uninstall numpy -y
          python -m pip uninstall scipy -y

      - name: Install Dependencies for Linux
        run: |
          sudo apt-get install -y libfuse2
          sudo apt-get install -y ccache
          sudo apt-get install -y upx-ucl

      - name: Build on Linux
        run: >
          python -m nuitka
          --clang
          --msvc=latest
          --standalone
          --enable-plugin=pyqt5
          --disable-plugin=multiprocessing
          --nofollow-import-to=scipy
          --nofollow-import-to=numpy
          --assume-yes-for-downloads
          --disable-console
          --follow-import-to=Adapters
          --follow-import-to=MCSL2Lib
          --lto=no
          --output-dir=build
          --linux-icon=MCSL2.ico
          --company-name="MCSL Team"
          --product-name="MCSL 2"
          --file-version=${{ matrix.mcsl2version }}
          --product-version=${{ matrix.mcsl2version }}
          --file-description="MC Server Launcher 2"
          --include-data-dir=resource/dark=resource/dark
          --include-data-dir=resource/light=resource/light
          --remove-output
          --copyright="Copyright ©MCSL Team. All right reserved."
          MCSL2.py

      - name: Delete Useless Files and Compress with upx
        run: |
          cd build
          cd MCSL2.dist
          rm -r certifi
          rm -r zstandard
          sudo rm .\build\MCSL2.dist\libQt5Quick.so.5
          sudo rm .\build\MCSL2.dist\libQt5Qml.so.5
          sudo rm .\build\MCSL2.dist\libQt5QmlModels.so.5
          upx -9 .\*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-${{ runner.os }}-${{ matrix.architecture }}
          path: |
            build/MCSL2.dist/**/*

  Release:
    runs-on: ubuntu-latest

    needs:
      - Windows
      - Linux
    
    strategy:
      matrix:
        mcsl2version: 
          - 2.2.1.1

    steps:

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Install Tools
        run: sudo apt install p7zip-full -y

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          path: repo
          
      - name: Compress Artifacts
        run: |
          7z a -tzip "MCSL2-${{ matrix.mcsl2version }}-Windows-x64.zip" "./MCSL2-Windows-x64/*"
          7z a -tzip "MCSL2-${{ matrix.mcsl2version }}-Windows-x86.zip" "./MCSL2-Windows-x86/*"
          7z a -tzip "MCSL2-${{ matrix.mcsl2version }}-Windows-arm64.zip" "./MCSL2-Windows-arm64/*"
          7z a -tzip "MCSL2-${{ matrix.mcsl2version }}-Linux-x64.zip" "./MCSL2-Linux-x64/*"
          7z a -tzip "MCSL2-${{ matrix.mcsl2version }}-Linux-x86.zip" "./MCSL2-Linux-x86/*"
          7z a -tzip "MCSL2-${{ matrix.mcsl2version }}-Linux-arm64.zip" "./MCSL2-Linux-arm64/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./repo/ChangeLog.md
          prerelease: false
          draft: false
          tag_name: v${{ matrix.mcsl2version }}
          files: |
            *.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
