name: Build and Release

on: [push, workflow_dispatch]

permissions: write-all

jobs:
  BuildWindowsVersion:
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
        architecture:
          - x64
          - x86
        mcsl2version: 
          - 2.1.3.6

    runs-on: ${{ matrix.os }}

    steps:

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt

      - name: Update Pip
        run: |
          python -m pip install pip setuptools -U


      - name: Install Requirements
        run: |
          python -m pip install -r requirements.txt -r requirements.dev.txt

      - name: Build on Windows
        run: >
          python -m nuitka 
          --mingw64
          --standalone
          --enable-plugin=pyqt5
          --onefile
          --output-dir=build
          --assume-yes-for-downloads
          --windows-disable-console
          --windows-icon-from-ico=MCSL2.ico
          --windows-company-name="LxHTT"
          --windows-product-name="MCSL 2"
          --windows-file-version=${{ matrix.mcsl2version }}
          --windows-product-version=${{ matrix.mcsl2version }}
          --windows-file-description="MC Server Launcher 2"
          MCSL2.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-${{ runner.os }}-${{ matrix.architecture }}
          path: |
            build/*.exe

  BuildmacOSVersion:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
        architecture:
          - x64
        mcsl2version: 
          - 2.1.3.6

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt

      - name: Update Pip
        run: |
          python -m pip install pip setuptools -U

      - name: Install Requirements
        run: |
          python -m pip install -r requirements.txt -r requirements.dev.txt

      - name: Build on macOS
        run: >
          python -m nuitka
          --standalone
          --onefile
          --enable-plugin=pyqt5
          --macos-create-app-bundle
          --macos-signed-app-name="com.lxhtt.mcsl2"
          --macos-app-name="MCSL2"
          --macos-app-mode="gui"
          --output-dir=build
          --assume-yes-for-download
          --disable-console
          --macos-app-version=${{ matrix.mcsl2version }}
          --macos-app-icon=MCSL2.icns
          MCSL2.py

      - name: Fix App Bundle on macOS
        run: |
           chmod +x build/MCSL2.app/Contents/MacOS/MCSL2
           rm -r build/MCSL2.app/Contents/_CodeSignature
           mkdir build/MCSL2.app/Contents/Resources
           cp MCSL2.icns build/MCSL2.app/Contents/Resources/MCSL2.icns
           cp Info.plist build/MCSL2.app/Contents/Resources
           cp Info.plist build/MCSL2.app/Contents
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-${{ runner.os }}-${{ matrix.architecture }}
          path: |
            build/*.app/**/*

  BuildLinuxVersion:
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
        architecture:
          - x64
          - x86
        mcsl2version: 
          - 2.1.3.6

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt

      - name: Update Pip
        run: |
          python -m pip install pip setuptools -U

      - name: Install Deps for Linux
        run: |
          sudo apt-get install -y libfuse2

      - name: Install Project Deps
        run: |
          python -m pip install -r requirements.txt -r requirements.dev.txt

      - name: Build on Linux
        run: >
          python -m nuitka
          --standalone
          --enable-plugin=pyqt5
          --onefile
          --output-dir=build
          --assume-yes-for-downloads
          --linux-icon=MCSL2.ico
          --company-name="LxHTT"
          --product-name="MCSL 2"
          --file-version=${{ matrix.mcsl2version }}
          --product-version=${{ matrix.mcsl2version }}
          --file-description="MC Server Launcher 2"
          MCSL2.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-${{ runner.os }}-${{ matrix.architecture }}
          path: |
            build/*.bin

  CreateRelease:
    runs-on: ubuntu-latest

    needs:
      - BuildWindowsVersion
      - BuildmacOSVersion
      - BuildLinuxVersion
    
    strategy:
      matrix:
        mcsl2version: 
          - 2.1.3.6

    steps:

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Install Tools
        run: sudo apt install p7zip-full -y

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          path: repo
          
      - name: Compress Artifacts
        run: |
          7z a "MCSL2-${{ matrix.mcsl2version }}-Linux-x64.zip" "./MCSL2-Linux-x64/*"
          7z a "MCSL2-${{ matrix.mcsl2version }}-Linux-x86.zip" "./MCSL2-Linux-x86/*"
          7z a "MCSL2-${{ matrix.mcsl2version }}-Windows-x64.zip" "./MCSL2-Windows-x64/*" -ir!"./repo/Tools/Aria2/aria2c.exe" -o"MCSL2/Aria2"
          7z a "MCSL2-${{ matrix.mcsl2version }}-Windows-x86.zip" "./MCSL2-Windows-x86/*" -ir!"./repo/Tools/Aria2/aria2c.exe" -o"MCSL2/Aria2"
          7z a "MCSL2-${{ matrix.mcsl2version }}-macOS-x64.zip" "./MCSL2-macOS-x64/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./repo/ChangeLog.md
          prerelease: true
          draft: false
          tag_name: v${{ matrix.mcsl2version }}
          files: |
            MCSL2-${{ matrix.mcsl2version }}-Linux-x64.zip
            MCSL2-${{ matrix.mcsl2version }}-Linux-x86.zip
            MCSL2-${{ matrix.mcsl2version }}-Windows-x64.zip
            MCSL2-${{ matrix.mcsl2version }}-Windows-x86.zip
            MCSL2-${{ matrix.mcsl2version }}-macOS-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
