name: Detect Depends

on: workflow_dispatch

permissions: write-all

jobs:
  Windows:
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-2019
        architecture:
          - x64

    runs-on: ${{ matrix.os }}

    steps:

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Update Pip and Install Requirements
        shell: pwsh
        run: |
          python -m pip install -U pip setuptools
          echo "-----------------------------------------"
          python -m pip list
          echo "-----------------------------------------"
          python -m pip install -r requirements.txt
          python -m pip uninstall numpy -y
          python -m pip uninstall scipy -y
          echo "-----------------------------------------"
          python -m pip list