name: Build with Nuitka

on: [push, workflow_dispatch]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      # nuitka action 依赖全局环境的py包，这里不能创建虚拟环境
      - name: Install Dependencies
        run: |
          python -m pip install poetry pip setuptools -U
          poetry config virtualenvs.create false
          poetry run poetry install --no-root
          
      - name: Install Deps for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libfuse2

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          onefile: true
          enable-plugins: pyqt5
          windows-icon-from-ico: pack.ico
          windows-company-name: LxHTT
          windows-product-name: MCSL2
          windows-file-version: 2.0.0
          windows-product-version: 2.0.0
          windows-file-description: A Minecraft Server Launcher

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
